apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-app:1.0.1
          ports:
            - containerPort: 5000
      tolerations:
      - key: "class"
        operator: "Equal"
        value: "vip"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: flask-app
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                  - key: capability
                    operator: In
                    values:
                      - powerful
            - weight: 1
              preference:
                matchExpressions:
                  - key: usage
                    operator: In
                    values:
                      - normal
            - weight: 2
              preference:
                matchExpressions:
                  - key: usage
                    operator: In
                    values:
                      - backup
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-t1
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
